# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-17 13:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkedhr', '0063_auto_20180614_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skill', to=settings.AUTH_USER_MODEL),
        ),
    ]
