# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-17 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkedhr', '0064_auto_20180617_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_list',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='linkedhr.SkillList'),
        ),
    ]
