# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-19 12:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('linkedhr', '0068_auto_20180618_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='zip_code',
            field=models.CharField(default=datetime.datetime(2018, 6, 19, 12, 7, 19, 217342, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
