# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-19 12:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('linkedhr', '0069_company_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='zip_code',
            field=models.CharField(default=datetime.datetime(2018, 6, 19, 12, 54, 31, 43795, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
