# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-23 12:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('linkedhr', '0070_branch_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruitment',
            name='sub_position',
            field=models.CharField(default=datetime.datetime(2018, 6, 23, 12, 55, 44, 952739, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
