# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-23 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkedhr', '0072_auto_20180623_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkedhr.Branch'),
        ),
    ]
