# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-23 14:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkedhr', '0073_auto_20180623_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recruitment', to=settings.AUTH_USER_MODEL),
        ),
    ]
