# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-25 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedhr', '0074_auto_20180623_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='count_update',
            field=models.IntegerField(default=0),
        ),
    ]
