# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-07 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedhr', '0076_auto_20180625_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created', '-updated'],
            },
        ),
    ]
