# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-09 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkedhr', '0077_jobpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='job_package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobpackage_recruitment', to='linkedhr.JobPackage'),
            preserve_default=False,
        ),
    ]
