# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-13 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_auto_20180610_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(upload_to=document.models.content_file_name, validators=[document.models.validate_file_extension]),
        ),
    ]
