# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-18 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_auto_20180613_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
